version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      actions:
        patterns: ["*"]
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      build:
        patterns: ["*"]
  - package-ecosystem: "pip"
    directory: "tests"
    schedule:
      interval: "monthly"
    groups:
      tests:
        patterns: ["*"]
  - package-ecosystem: "pip"
    directory: "docs"
    schedule:
      interval: "monthly"
    groups:
      docs:
        patterns: ["*"]
  - package-ecosystem: "pip"
    directory: "benchmark"
    schedule:
      interval: "monthly"
    groups:
      benchmark:
        patterns: ["*"]
  - package-ecosystem: "pip"
    directory: "scripts"
    schedule:
      interval: "monthly"
    groups:
      scripts:
        patterns: ["*"]
