repos:
- repo: local
  hooks:
  - id: sort_all
    name: Sort __all__
    entry: python3 scripts/sort_all.py
    language: python
    types: [ python ]
- repo: https://github.com/hadialqattan/pycln
  rev: v1.1.0
  hooks:
    - id: pycln
- repo: https://github.com/pycqa/isort
  rev: 5.10.1
  hooks:
    - id: isort
- repo: https://github.com/ambv/black
  rev: 21.12b0
  hooks:
  - id: black
    args: [-C]
- repo: https://github.com/PyCQA/flake8
  rev: 4.0.1
  hooks:
  - id: flake8
    exclude: ^examples/.*\.py$
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.930
  hooks:
  - id: mypy
    exclude: ^examples/.*\.py$
