default_language_version:
    python: python3.10
repos:
- repo: local
  hooks:
  - id: sort_all
    name: Sort __all__
    entry: python3 scripts/sort_all.py
    language: python
    types: [ python ]
- repo: https://github.com/ambv/black
  rev: 21.9b0
  hooks:
  - id: black
    language_version: python3.6
    args: [-C]
- repo: https://github.com/PyCQA/flake8
  rev: 3.9.2
  hooks:
  - id: flake8
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.910-1
  hooks:
  - id: mypy
