site_name: Apischema
repo_name: wyfo/apischema
repo_url: https://github.com/wyfo/apischema

theme:
  name: material
  palette:
    scheme: preference
    primary: green
    accent: indigo

nav:
- index.md
- data_model.md
- de_serialization.md
- json_schema.md
- validation.md
- conversions.md
- GraphQL:
  - Overview: graphql/overview.md
  - graphql/data_model_and_resolvers.md
  - graphql/schema.md
- Examples:
  - OpenRPC: examples/open_rpc.md
  - examples/sqlalchemy.md
  - examples/pydantic_support.md
  - examples/attrs_support.md
  - examples/subclasses_union.md
  - examples/recoverable_fields.md
- benchmark.md
- pydantic_difference.md
- Releases: https://github.com/wyfo/apischema/releases


markdown_extensions:
- markdown.extensions.codehilite:
    guess_lang: false
- markdown_include.include:
    base_path: examples
- toc:
    permalink: True
#    toc_depth: 3
- admonition
- codehilite
- extra
- attr_list

plugins:
- search
- exclude:
    glob:
    - requirements.txt

