name: CD

on:
  workflow_dispatch:
  release:
    types:
    - published

jobs:
  build_sdist:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: scripts/cythonize.sh
    - run: pipx run build --sdist
    - uses: actions/upload-artifact@v2
      with:
        name: dist
        path: dist/*.tar.gz
  build_wheels:
    name: Wheel on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2022, windows-2019, ubuntu-20.04, ubuntu-18.04, macos-11, macos-10.15]
    steps:
      - uses: actions/checkout@v2
      - run: scripts/cythonize.sh
      - uses: pypa/cibuildwheel@v2.0.0
        with:
          CIBW_TEST_COMMAND: pytest {project}/tests --ignore=tests/__generated__/test_recursive_postponned.py
          CIBW_BEFORE_TEST: pip install -r tests/requirements.txt
          CIBW_TEST_SKIP: "*universal2:arm64"
      - uses: actions/upload-artifact@v2
        with:
          name: dist
          path: wheelhouse/*.whl
  publish:
    needs: [build_sdist, build_wheels]
    runs-on: ubuntu-latest
    if: github.event_name == 'release' && github.event.action == 'published'
    steps:
    - uses: actions/download-artifact@v2
      with:
        name: dist
        path: dist
    - uses: pypa/gh-action-pypi-publish@v1.4.2
      with:
        password: ${{ secrets.PYPI_TOKEN }}